
spring:
  data:
    mongodb:
      uri: mongodb+srv://${DB_USER}:${DB_PASSWORD}@webfluxcoursecluster.bdepgu1.mongodb.net/${DB_NAME:webflux-course}?retryWrites=true&w=majority&appName=WebfluxCourseCluster
      auto-index-creation: true
  application:
    name: webflux-course
